services:
  postgres:
    image: postgres:17.4
    container_name: reflecta-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: